dists:
    ubuntu:
      pm_type: "apt"
      versions:
        -
          version_id: "22.04"
          version_name: "jammy"
        -
          version_id: "20.04"
          version_name: "focal"
      repos:
        DEFREPO:
          archive: "https://mirrors.edge.kernel.org/ubuntu/dists/$version_name/"
          subrepos: ["main", "universe", "multiverse", "restricted"]
        updates:
          archive: "https://mirrors.edge.kernel.org/ubuntu/dists/$version_name-updates/"
          subrepos: ["main", "universe", "multiverse", "restricted"]
        security:
          archive: "https://mirrors.edge.kernel.org/ubuntu/dists/$version_name-security/"
          subrepos: ["main", "universe", "multiverse", "restricted"]
        backports:
          archive: "https://mirrors.edge.kernel.org/ubuntu/dists/$version_name-backports/"
          subrepos: ["main", "universe", "multiverse", "restricted"]
        vscode:
          archive: "https://packages.microsoft.com/repos/vscode/dists/stable/"
          subrepos: ["main"]

    fedora:
      pm_type: "dnf"
      versions:
        - version_id: "37"
        - version_id: "36"
      repos:
        DEFREPO:
          archive: "https://mirrors.edge.kernel.org/fedora/releases/$version_id/Everything/x86_64/os/"
        updates:
          archive: "https://mirrors.edge.kernel.org/fedora/updates/$version_id/Everything/x86_64/"
        google_chrome:
          version_agnostic: true
          archive: "https://dl.google.com/linux/chrome/rpm/stable/x86_64/"

    archlinux:
      pm_type: "pacman"
      archive: "https://mirror.cyberbits.eu/archlinux/$repo/os/x86_64/"
      repos:
        core: {}
        community: {}
        extra: {}
        arch4edu:
          archive: "https://mirror.lesviallon.fr/arch4edu/x86_64/"
  